version: "3"

services:
  db:
    image: mysql:8.0
    container_name: db_blog_xdb
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: dogwordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 42333:3306
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wp:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile_local
    container_name: wp_blog_xdb
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      XDEBUG_CONFIG: remote_host=host.docker.internal
    volumes:
      - ./src/wordpress:/var/www/html
      - ./src/themes/dogeared:/var/www/html/wp-content/themes/dogeared
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge